//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s3357335_a2_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingItem
    {
        public int BookingID { get; set; }
        public int SessionID { get; set; }
        public int SeatNum { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual MovieSession MovieSession { get; set; }
    }
}
