//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s3357335_a2_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.BookingItems = new HashSet<BookingItem>();
        }
    
        public int BookingID { get; set; }
        public string CustomerEmail { get; set; }
        public int TicketNum { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual ICollection<BookingItem> BookingItems { get; set; }
    }
}
