//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s3357335_a2_client
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSession
    {
        public MovieSession()
        {
            this.BookingItems = new HashSet<BookingItem>();
        }
    
        public int SessionID { get; set; }
        public int MovieID { get; set; }
        public int CineplexID { get; set; }
        public System.DateTime ShowTime { get; set; }
        public int SeatSold { get; set; }
        public int MaxSeatNum { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<BookingItem> BookingItems { get; set; }
        public virtual Cineplex Cineplex { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
