//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s3357335_a2_client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MovieEntities : DbContext
    {
        public MovieEntities()
            : base("name=MovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Booking> Bookings { get; set; }
        public DbSet<BookingItem> BookingItems { get; set; }
        public DbSet<Cineplex> Cineplexes { get; set; }
        public DbSet<CorporateEvent> CorporateEvents { get; set; }
        public DbSet<Enquiry> Enquiries { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<MovieComingSoon> MovieComingSoons { get; set; }
        public DbSet<MovieSession> MovieSessions { get; set; }
    
        public virtual ObjectResult<GetAllComingMovie_Result> GetAllComingMovie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllComingMovie_Result>("GetAllComingMovie");
        }
    
        public virtual ObjectResult<GetAllCorporateEvent_Result> GetAllCorporateEvent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCorporateEvent_Result>("GetAllCorporateEvent");
        }
    
        public virtual ObjectResult<GetAllMovie_Result> GetAllMovie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllMovie_Result>("GetAllMovie");
        }
    }
}
